### ISSUE TITLE
Generate recipes for own ROS2 packages

### ISSUE THREAD

**Issue by TablewareBox** [RoboStack/vinca#63]
Hi vinca developers, I'm developing my own ROS pakcage (maybe call it `lab_msgs`), can I use `vinca` and `boa` to build conda package of it? Are there any examples or documentation?

**Comment by Tobias-Fischer** [comment]
Yes you can :). Check out e.g. https://github.com/RoboStack/ros-noetic/tree/main/additional_recipes/ros-noetic-jackal-base

Let us know if you have questions.

**Comment by TablewareBox** [comment]
Thanks!

How can I specify `python` version of the built package? I found this always built to `python=3.11` even though I specify `python: 3.10` in `recipe.yaml`. My base env and env are all `python 3.10`.

My file:

```
package:
  name: ros-humble-ilabos-msgs
  version: 0.0.2
source:
  path: /Users/chang/Design_projects/LabOS/ILabOS/ilabos_msgs
  folder: ros-humble-ilabos-msgs/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 5
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
    - python >=3.10,<3.11
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - ros-humble-action-msgs
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.5 humble
    - python >=3.10,<3.11
  run:
    - ros-humble-action-msgs
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.5 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - python >=3.10,<3.11
```
